services:
  - type: web
    name: flask-playwright-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/ms-playwright"
